[package]
name = "simple_calculator"
version = "0.1.3"
authors = ["Jamil Ahmed"]
edition = "2018"
description = "First Library"
license = "MIT"
readme = "readme.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
